NodeBB/nodebb-theme-persona

templates/partials/topic/post.tpl
I noticed that the `post-signature` is nested into `content`, while fixing plugin-poll.
This is inconsistent with theme-lavender [templates/topic.tpl#L39-L42](https://github.com/NodeBB/nodebb-theme-lavender/blob/master/templates/topic.tpl#L39-L42).
=> signature outside of content

templates/groups/list.tpl
This should make the group-name option list lose the whitespace to the right of it as seen [here](https://community.nodebb.org/groups).
There was just a `row` class missing.
=> Fix nested row markup on groups page

templates/partials/menu.tpl
I thought just the user's username would be suitable as the alt text but you may want to change that to something like "Profile photo of...".
Fixes #137
=> Added alt text to navbar profile image

less/categories.less, less/topic.less
This fix is for topic `h1` headings but it may need to be applied to elements elsewhere as well.
Fixes #148
=> Break long worded topic headings

templates/topic.tpl
Not super important, but helpful for sub-themes.
=> Line up with other containers

templates/groups/details.tpl
- There is no CSS rule matching .icon here,
according to Chrome DevTools.
belongs NodeBB/NodeBB#4549 ('icon' would be passed to the modal as initial selection)
=> Remove .icon, make {group.icon} conditional

templates/partials/categories/item.tpl, templates/partials/topics_list.tpl
Would save me (i.e. the user's browser) a lot of conditionals, since post structure is almost, yet not completetly the same for teasers and post listings. I also don't like selecting DOM objects by classes (.teaser would do the trick, too), that much. Ya know, people writing their own themes and stuff :wink:
I'm onto changing theme-vanilla, theme-lavender and theme-quickstart, as well. There aren't any other official themes that need to be updated, are there?
=> Promote teaser to be components

lib/persona.js
fixes NodeBB/NodeBB#4483 by disabling touch event in slideout menu on non-xs screens
=> fixes NodeBB/NodeBB#4483

templates/partials/topic/post.tpl
This makes post parent buttons clickable even without JavaScript, which means search engines can see them.
It also means posts that are moved to a different topic can still be accessed through the button.
=> convert post parent button to a link

.gitignore, less/style.less, lib/persona.js
- Exclude `.vscode` directory
- `html` and `body` get `min-height: 100%`
- `#panel.slideout-panel` gets `min-height: 100vh` (100% viewport height)
- Don't need to call `loadNotificationsAndChat()` twice
- On menu close, return pagination to normal position
- As menu opens, reposition paginator to bottom of screen
=> Fixes #183: short body menu animation, paginator

less/modules/bottom-sheet.less
Don't override the background color of the bottom-sheet dropdown menu. It is already white on light themes and this makes white-on-white text on dark themes.
Fixes apapadimoulis/what-bugs#155.
=> Fix mobile profile dropdown menu on dark bootswatch themes

templates/partials/account/menu.tpl
=> Don't add a divider on every Profile Menu link.

templates/registerComplete.tpl
Increase column width for Registration Complete page to 12-col on mobile, 8-col otherwise. 
Fixes nodebb/nodebb#5229.
=> Increase column width of Terms of Use

less/style.less, templates/search.tpl
Fixes NodeBB/NodeBB#5206.
Use `btn-primary` for search button on search page as `btn-default` looks like an input field.
=> Minor UI fixes.

less/category.less, templates/partials/categories/item.tpl, templates/partials/menu.tpl, templates/partials/topic/post.tpl, templates/topic.tpl
There are still a lot of semantical errors, but this PR should at least fix all syntactical errors I found (related to escaping).
Also a regression is being fixed I introduced in #347 : I changed a div to a span, which contains non-inline content being inserted by nodebb. Solution was to move this span out of the surrounding h2 tag and change it back to a div.
For some reason the "subtopics image" shrunk by a couple of pixels during this process, everything else is almost exactly the same:
Before:
After: ![After](https://user-images.githubusercontent.com/8350879/32138316-d212becc-bc30-11e7-8698-c7cc09f4a260.png)
If that's a problem, and you could tell me how to fix it (I couldn't figure it out), I will do so.
=> Fix another bunch of HTML violations

less/header.less, lib/persona.js
https://github.com/NodeBB/NodeBB/issues/6170
=> Fixed navbar autohide after viewport resize

templates/partials/topic/post.tpl
It missed the `posts.user.` prefix and thus never iterated over anything since it is an undefined variable.
=> Fixed the listing of custom profile info on posts

templates/account/categories.tpl, templates/partials/account/category-item.tpl, templates/partials/account/menu.tpl, templates/partials/category/watch.tpl
This commit, together with the [pull request at NodeBB](https://github.com/NodeBB/NodeBB/pull/6648), adds a settings page to control your watched and ignored categories.
The page shows all categories in a flat view and the buttons do update as expected, changing the watched setting in a top level modifies the setting for all sub-categories.
=> Add settings page to control watched categories

less/chats.less, templates/partials/chats/message.tpl
This change moves the many icons that can possibly show in chat messages to a less obstructive place, most especially for the editing icons, to make hovering/editing messages less annoying.
Before:
Now:
All icons:
=> Move chat icons above message

languages/de/persona.json
Providing the German translation for `persona:mobile-menu-side` thanks to the fixing of issue #418.
=> Added German translation for persona:mobile-menu-side

less/topic.less
For the bookmarked class to be displayed in the right place, the parent should contain a relative position.
=> Fix bookmarked

templates/login.tpl
related to https://github.com/akhoury/nodebb-plugin-spam-be-gone/issues/32
=> added loginFormEntry in the login form, to support captcha on login page

less/modules/taskbar.less
For composers, the taskbar icon will now reflect the colour and
icon for the category you are posting in.
For chats, a proper chat icon is used.
In both, an "active" modal/composer will show a little eye icon
showing that it is active.
=> feat: Taskbar icon colour change + visibility icon

templates/partials/cookie-consent.tpl
It's a good practice to make target="_blank" links to cross-origin destination not give any control over original window to the site that's opened if it's not needed. And it's not needed here.
Also, lighthouse complains about it, so this small change will improve the "Best Practices" score there :)
=> Add rel="noopener" to cookie-consent

templates/partials/buttons/newTopic.tpl
I don't have the time to look into this enough to really make the "New Topic" button accessible. However, right now, it isn't accessible for keyboard navigation at all (as it's not registered as "clickable").
While these changes don't add actual "overall" accessibility to the pseudo button, it at least adds the ability for keyboard navigation tools to register it as a button (at least adding support for extensions like [Vimium](https://vimium.github.io/), etc.
(the button is now "clickable" using the keyboard)
=> Adding at least a tiny bit of accessibility to the New Topic button

less/topic.less
Upvote and downvote have padding, 0.5rem less on the sides w/ the vote count as that is also a button, padding added to vote count.
=> fix: nodebb/nodebb#8782

less/mixins.less, less/modules/necro-post.less, less/topic.less, less/variables.less, templates/partials/topic/event.tpl, templates/partials/topic/necro-post.tpl
I was hoping to take this base design and extend it in core to allow for "topic events", to allow plugins to add events to a topic when they happen.
e.g. Q&A plugin can add an event when the topic is marked solved (w/ link to solved pid)
e.g. Poll plugin can add an event when the poll closes
Note: In this particular implementation, I simply hacked the necro-post style to fit the timeline styling. Eventually, we'd want the necro-post labels to also be dynamically generated topic events.
Commits:
- feat: basic timeline-style styling for posts in a topic
- fix: mobile-style for timeline-style styling
=> Timeline-style design for a topic's posts

templates/partials/fork_thread_modal.tpl
**Done**:
- Static text replaced with the code for dynamic translation
P.S. Also take a look at #520 (same issue)
=> Fix: translate "fork thread" modal

public/persona.js
- Rewrote in vanilla js
- Takes into account the actual vertical height of the header from the top of viewport in addition to the header itself
- Themes often add stuff above the header, and so theme-related hacks will no longer be necessary
=> refactor: header padding calculations [breaking]

public/persona.js, scss/chats.scss, scss/groups.scss, scss/style.scss, scss/topic.scss, templates/header.tpl, templates/partials/chats/message-window.tpl, templates/topic.tpl
@pitaj said:
* Use sticky instead for navbar
* Keep var around for topic header and such
* But move the code so it gets set immediately as page loads
* Changed offset to just bottom of header (not including margin) so less `calc( .. - 20px)` is needed
=> refactor: improve panel offset code

less/topic.less
- chore: v12.1.7
- docs: update readme re: v2.x and v3.x usage
- fix: #10981, use fa-chevron-circle-up (and down) on upvoted and downvoted
=> Use fa-chevron-circle-up (and down) for upvoted and downvoted
