templates/partials/share_dropdown.tpl
Identical change to https://github.com/NodeBB/nodebb-theme-vanilla/pull/54
=> Changes to Android default.

templates/partials/topic/post.tpl
nodebb-plugin-cash requires this to render the amount.
https://community.nodebb.org/topic/145/nodebb-plugin-cash-cash-mod/38
=> Added custom_profile_info

templates/groups/details.tpl, templates/groups/list.tpl
Missing localizations in group details
=> Add missing localizations

templates/partials/topics_list.tpl
=> Use topic thumbnail when available

templates/chats.tpl
Adding missing localizations as I find them out.
=> Missing localization for "Send" button in chat

less/chats.less, less/header.less, less/notifications.less
This should fix issue [#3484](https://github.com/NodeBB/NodeBB/issues/3484) created on the NodeBB repo.
=> Make notification and chat avatars rounded

templates/groups/details.tpl
This should fix issue [#3482](https://github.com/NodeBB/NodeBB/issues/3482) created on the NodeBB repo.
=> Make the group header fit the container

templates/account/edit.tpl, templates/groups/details.tpl, templates/partials/move_thread_modal.tpl, templates/partials/post_bar.tpl, templates/reset.tpl, templates/reset_code.tpl
I've replaced inline styles where possible. The inline styles that remain use JavaScript variables. Fixes #128
=> Replaced inline styles where possible

templates/partials/modals/upload_picture_modal.tpl
=> Fix "for" attribute and form control mismatch

templates/partials/modals/change_picture_modal.tpl, templates/partials/modals/upload_picture_from_url_modal.tpl, templates/partials/modals/upload_picture_modal.tpl
=> Establish a relationship between modals and their labels

templates/login.tpl, templates/popular.tpl, templates/recent.tpl, templates/register.tpl, templates/reset.tpl, templates/tag.tpl, templates/tags.tpl, templates/unread.tpl
This is just a suggestion. Fixes #140
=> Remove strong importance from alert text

less/header.less
=> Fix text size in dropdowns

less/categories.less, less/category.less, templates/categories.tpl, templates/partials/categories/item.tpl
I've also changed the category titles from `<h1>` for `<h2>` as discussed in the issue comments.
This fixes #132.
=> Move elements to contexts where they are allowed

templates/tags.tpl
This is just a suggestion. Fixes #143
=> Put tag search box at top of page

less/topic.less, templates/partials/topic/post-menu.tpl
There's a consecutive PR on the main repo to enable this being useful: https://github.com/NodeBB/NodeBB/pull/3604
=> Added post tools loop for plugins.

less/chats.less
=> Fix width of chat input field and submit button

less/header.less, templates/partials/menu.tpl
=> Add transition to search bar

less/header.less
=> Fixed advanced search button not showing

less/chats.less, templates/chats.tpl
https://github.com/NodeBB/NodeBB/issues/4121
=> initiate chat from chat page

templates/partials/account/header.tpl
showHidden is basically isAdminOrSelf
https://github.com/NodeBB/NodeBB/blob/master/src/controllers/accounts/helpers.js#L82
=> fixes #219

lib/persona.js
=> don't show user card for guest

templates/modules/usercard.tpl, templates/partials/account/header.tpl, templates/partials/account/menu.tpl
=> don't show follow and chat for banned users

templates/partials/topic/post.tpl
=> fix toPid link for post by guest

templates/partials/topics_list.tpl
=> remove user redirect for guest

less/topic.less
=> Add min-width to code blocks

templates/header.tpl
=> fix "No way to access all notifications on mobile"

templates/partials/groups/memberlist.tpl
=> for proper styling in ACP

templates/chats.tpl, templates/partials/chat_recent_room.tpl
mark room unread on new message on `/chats` page
=> mark room unread on new message

less/header.less
other languages string are longer :)
=> missing padding for longer strings

templates/topic.tpl
=> Duplicate widget derp in topics.tpl

templates/partials/paginator.tpl
=> fix mobile pagination

lib/admin.js, library.js, plugin.json, templates/admin/plugins/persona.tpl, templates/partials/categories/item.tpl
=> ability to toggle display of subcategories on categories page

less/header.less
=> proper positioning of notification count display on IE

library.js, templates/admin/plugins/persona.tpl, templates/partials/categories/item.tpl
=> add switch for last posts in category view

less/header.less, templates/header.tpl
add bootswatch skin class to body tag to adjust styling.
=> add bootswatch skin class to body tag

less/category.less, templates/partials/topics_list.tpl
Display topic select (check mark) on hover over user avatar. Also display topic creator username in topics list except on mobile screens.
=> display topic select on hover

templates/partials/topics_list.tpl
for https://github.com/NodeBB/NodeBB/pull/4858
=> add data-set attribute to topics_list

less/topic.less, templates/partials/fork_thread_modal.tpl
also disable "Fork topic" button by default.
=> change selected post highlight when forking topic

templates/account/info.tpl, templates/account/settings.tpl
for https://github.com/NodeBB/NodeBB/pull/4959
=> Move login sessions to account info route

less/register.less, templates/register.tpl
for https://github.com/NodeBB/NodeBB/pull/4987
=> minor design tweaks to register page

less/register.less, templates/unread.tpl
so they don't look like this...
also adjust margins on login page.
=> adjust dropdown layout on unread page

less/account.less, templates/account/edit/password.tpl
to match register page for displaying validations
for NodeBB/NodeBB#5099
=> modify user -> edit password screen 

less/modules/bottom-sheet.less
also make backdrop a bit darker
=> more padding for bottom sheet items

less/modules/bottom-sheet.less, templates/partials/account/menu.tpl, templates/partials/category/sort.tpl, templates/partials/category/tools.tpl, templates/partials/category/watch.tpl, templates/partials/thread_tools.tpl, templates/partials/topic/post-menu.tpl, templates/partials/topic/sort.tpl, templates/partials/topic/watch.tpl
want to make a dropdown to use bottom sheet on mobile?  just add `bottom-sheet` class to the dropdown
=> generic class for bottom-sheet

less/topic.less, templates/partials/topic/post.tpl
=> UI for replies-to-post

templates/groups/list.tpl, templates/popular.tpl, templates/recent.tpl, templates/tags.tpl, templates/unread.tpl, templates/users.tpl
=> Widget placement fix

templates/footer.tpl, templates/header.tpl
=> Support customHTML/customJS

templates/header.tpl
This PR adds alt attributes to every img tag in this repo to satisfy the HTML validator, also a minor "violation" regarding a single style element has been fixed.
I'm not exactly sure if the alt description is actually good, feel free to suggest better descriptions
=> Remove uneccessary text/css definition

less/modules/bottom-sheet.less
Makes bottom sheet full width for RTL languages too.
=> Fix bottom sheet for RTL languages

templates/partials/account/header.tpl
Buttons for editing, deleting, changing items blocked for guests and other users on our profile.
=> Block changing items.

less/account.less, less/category.less, less/topic.less, less/users.less, package.json, templates/account/info.tpl, templates/flags/detail.tpl, templates/flags/list.tpl, templates/groups/details.tpl, templates/partials/categories/lastpost.tpl, templates/partials/chats/message.tpl, templates/partials/chats/user.tpl, templates/partials/groups/list.tpl, templates/partials/groups/memberlist.tpl, templates/partials/menu.tpl, templates/partials/modals/votes_modal.tpl, templates/partials/posts_list.tpl, templates/partials/quick-search-results.tpl, templates/partials/slideout-menu.tpl, templates/partials/topic/post.tpl, templates/partials/topic/quickreply.tpl, templates/partials/topics_list.tpl, templates/partials/users_list.tpl, templates/search.tpl, templates/users.tpl
=> Theme changes for buildAvatar

less/chats.less, templates/categories.tpl, templates/category.tpl, templates/groups/details.tpl, templates/groups/list.tpl, templates/popular.tpl, templates/recent.tpl, templates/tags.tpl, templates/top.tpl, templates/topic.tpl, templates/unread.tpl, templates/users.tpl
if this https://github.com/NodeBB/NodeBB/pull/5444 gets merged
=> changing widget-* to data-widget-*

languages/tr/persona.json
=> add turkish translation

templates/partials/modals/post_history.tpl
=> feat: add post diff remove button

templates/partials/modals/upload_file_modal.tpl, templates/partials/modals/upload_picture_from_url_modal.tpl
**Done**:
- Static text replaced with the code for dynamic translation
=> fix: "close" button translations on modals

templates/account/profile.tpl
see NodeBB/nodebb-theme-harmony#24
=> feat: add rel=me and remove redundant noopener - master branch
